project:
  type: default

format:
  pdf:
    documentclass: IEEEtran
    classoption: [lettersize, journal]
    pdf-engine: pdflatex
    number-sections: true
    keep-tex: true
    include-in-header:
      - ieee-header.tex
    geometry:
      - margin=1in
    fontsize: 10pt
    papersize: letter

bibliography: references.bib
csl: ieee.csl


